### ISSUE TITLE
"Object.entries is not a function" error

### ISSUE THREAD

**Issue by readtedium** [nuxt-community/content-template#14]
Receiving this error upon launch, which is preventing the page from displaying the desired content:

```
 WARNING  Compiled with 1 warnings                                     11:09:10 AM

 warning  in ./content/HelloWorld.comp.md

Module build failed: TypeError: Object.entries is not a function
    at mergeParserRules (/Users/Ernie.Smith/Documents/nuxtent/sfb/node_modules/nuxtent/dist/loader.js:39:43)
    at mdCompParser (/Users/Ernie.Smith/Documents/nuxtent/sfb/node_modules/nuxtent/dist/loader.js:95:31)
    at Object.module.exports (/Users/Ernie.Smith/Documents/nuxtent/sfb/node_modules/nuxtent/dist/loader.js:124:20)

 @ ./content \.comp\.md$
 @ ./.nuxt/plugins.markdownComponents.template.4020a60a.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi webpack-hot-middleware/client?name=client&reload=true&timeout=3000&path=/__webpack_hmr ./.nuxt/client.js
```

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/nuxtent-template/issues/c11">#c11</a>)</em></sub></div>

**Comment by alidcastano** [comment]
What version are you using

**Comment by jamesray** [comment]
+1
