### ISSUE TITLE
Cannot read property 'get' of undefined

### ISSUE THREAD

**Issue by bas72** [nuxt-community/content-template#15]
Fresh install of nuxtent template, when clicking see your first post it returns this error. Please advise.

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/nuxtent-template/issues/c9">#c9</a>)</em></sub></div>

**Comment by alidcast** [comment]
Hey, sorry I haven't had a chance to update the template to latest version

**Comment by vsimko** [comment]
same problem here.
I also noticed that there are deprecated `isClient` and `isServer` being used

btw. related issue https://github.com/nuxt-community/nuxtent-module/issues/133

**Comment by janzheng** [comment]
this is still broken... your starter template doesn't work :(

**Comment by mahdi2013safari** [comment]
I have this issue 
I install nodejs v12.13.1
and npm v6.12.1
```
Error: EPERM: operation not permitted, mkdir 'C:\Users\hello'
TypeError: Cannot read property 'get' of undefined
    at errorMessage (C:\Program Files\nodejs\node_modules\npm\lib\utils\error-message.js:38:39)
    at errorHandler (C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:201:13)
    at C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js:78:20
    at cb (C:\Program Files\nodejs\node_modules\npm\lib\npm.js:225:22)
    at C:\Program Files\nodejs\node_modules\npm\lib\npm.js:263:24
    at C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:81:7
    at Array.forEach (<anonymous>)
    at C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:80:13
    at f (C:\Program Files\nodejs\node_modules\npm\node_modules\once\once.js:25:25)
    at afterExtras (C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:171:20)
C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:97
  var doExit = npm.config.loaded ? npm.config.get('_exit') : true
```
