### ISSUE TITLE
Error: render function or template not defined in component: anonymous

### ISSUE THREAD

**Issue by ghost** [nuxt-community/content-template#6]
Hi,

When I `yarn generate`, I have this message : `TypeError: Nuxt is not a constructor`
```
[root@xx]# yarn generate
yarn generate v0.27.5
$ HOST=myipvps PORT=3000 nuxtent generate
  nuxt:generate Generating... +0ms
/home/nginx/domains/xx.fr/public/xx/node_modules/nuxtent/bin/nuxtent-generate:58
const nuxt = new Nuxt(options)
             ^

TypeError: Nuxt is not a constructor
    at Object.<anonymous> (/home/nginx/domains/xx.fr/public/xx/node_modules/nuxtent/bin/nuxtent-generate:58:14)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/nginx/domains/xx.fr/public/xx/node_modules/nuxtent/bin/nuxtent:26:1)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Function.Module.runMain (module.js:609:10)
    at startup (bootstrap_node.js:158:16)
error Command failed with exit code 1.
```

here my package.json : 

```
{
  "name": "stnetwork",
  "version": "1.0.0",
  "description": "Nuxt.js Content Site",
  "author": "",
  "private": true,
  "dependencies": {
    "@nuxtjs/axios": "latest",
    "nuxt": "1.0.0-alpha.3",
    "nuxtent": "^0.2.77"
  },
  "scripts": {
    "dev": "HOST=myipvps PORT=3000 nuxt",
    "build": "nuxt build",
    "start": "nuxt start",
    "generate": "HOST=myipvps PORT=3000 nuxtent generate",
    "lint": "eslint --ext .js,.vue --ignore-path .gitignore .",
    "deploy": "push-dir --dir=dist --branch=gh-pages --cleanup",
    "precommit": "npm run lint"
  },
  "devDependencies": {
    "babel-eslint": "^7.1.1",
    "eslint": "^3.15.0",
    "eslint-config-standard": "^6.2.1",
    "eslint-loader": "^1.6.1",
    "eslint-plugin-html": "^2.0.0",
    "eslint-plugin-promise": "^3.4.1",
    "eslint-plugin-standard": "^2.0.1"
  }
}
```

my nuxtent.config.json : 

```
module.exports = {
  content: {
    permalink: ':slug',
    page: '/_content',
    generate: [ // for static build
      'get', 'getAll'
    ],
    isPost: false
  },

  api: {
    baseURL: process.env.NODE_ENV === 'production'
      ? 'http://myipvps:3000'
      : 'http://myipvps:3000'
  }
}
```

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/nuxtent-template/issues/c6">#c6</a>)</em></sub></div>

**Comment by ghost** [comment]
Oh I solved it by `yarn global add nuxt`, now I have this message : 
```
==== Error report ====
Route: '/hello-world'
Error: render function or template not defined in component: anonymous
    at normalizeRender (/home/nginx/domains/xx.fr/public/xx/node_modules/vue-server-renderer/build.js:6873:13)
    at renderComponentInner (/home/nginx/domains/xx.fr/public/xx/node_modules/vue-server-renderer/build.js:6997:3)
    at renderComponent (/home/nginx/domains/xx.fr/public/xx/node_modules/vue-server-renderer/build.js:6968:5)
    at RenderContext.renderNode (/home/nginx/domains/xx.fr/public/xx/node_modules/vue-server-renderer/build.js:6884:5)
    at RenderContext.next (/home/nginx/domains/xx.fr/public/xx/node_modules/vue-server-renderer/build.js:2189:14)
    at cachedWrite (/home/nginx/domains/xx.fr/public/xx/node_modules/vue-server-renderer/build.js:2049:9)
    at renderStringNode (/home/nginx/domains/xx.fr/public/xx/node_modules/vue-server-renderer/build.js:7067:5)
    at RenderContext.renderNode (/home/nginx/domains/xx.fr/public/xx/node_modules/vue-server-renderer/build.js:6882:5)
    at RenderContext.next (/home/nginx/domains/xx.fr/public/xx/node_modules/vue-server-renderer/build.js:2189:14)
    at cachedWrite (/home/nginx/domains/xx.fr/public/xx/node_modules/vue-server-renderer/build.js:2049:9)
    at renderElement (/home/nginx/domains/xx.fr/public/xx/node_modules/vue-server-renderer/build.js:7108:5)
    at renderNode (/home/nginx/domains/xx.fr/public/xx/node_modules/vue-server-renderer/build.js:6886:5)
    at renderComponentInner (/home/nginx/domains/xx.fr/public/xx/node_modules/vue-server-renderer/build.js:7004:3)
    at renderComponent (/home/nginx/domains/xx.fr/public/xx/node_modules/vue-server-renderer/build.js:6968:5)
    at renderNode (/home/nginx/domains/xx.fr/public/xx/node_modules/vue-server-renderer/build.js:6884:5)
    at renderComponentInner (/home/nginx/domains/xx.fr/public/xx/node_modules/vue-server-renderer/build.js:7004:3)
  nuxt:generate Generate done +10s
Done in 11.19s.
```

**Comment by ghost** [comment]
I no longer have the message of the "error report", but I can't access to /hello-world

![image](https://user-images.githubusercontent.com/26366663/29818936-b911272a-8cbe-11e7-99ef-7ee0a667e2c5.png)

**Comment by alidcast** [comment]
Related to https://github.com/nuxt-community/nuxtent-module/issues/34

markdown components do not work yet with latest Nuxt versions. Take out component and everything should work :)

**Comment by ghost** [comment]
Ok I did but I also have `TypeError: Nuxt is not a constructor` message when I have 
`"generate": "NODE_ENV='production' IS_STATIC=true nuxtent generate"` instead of 
`"generate": "NODE_ENV='production' IS_STATIC=true nuxt generate"`

**Comment by alidcast** [comment]
sorry Nuxt was in an unstable version when I built Nuxtent.

`nuxtent generate` only works with latest versions. But those versions do not yet work with markdown components (hence, error with template) since Nuxt's upgrade broke something that I haven't yet had time to fix

**Comment by ghost** [comment]
no problem I should be on which version of nuxt for that all work well ?

**Comment by alidcast** [comment]
rc4 or higher should work for `nuxtent generate`. If you don't care about static builds and what to use markdown components, use `rc3` or lower.  The sites that I have published with nuxtent use markdown components so they are deployed as applications.
